#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    ERR_SUCCESS,
    ERR_FAIL,
    ERR_INVALID_ARGUMENT,
    ERR_INVALID_ALIGN,
    ERR_OUT_OF_BOUNDS,
    ERR_CORRUPT,
    ERR_BIT_CLEAR,
    ERR_UNINITIALIZED,
    ERR_NULL_PTR,
    ERR_NO_COMMIT,
    ERR_NO_RECORD
} flash_error;

typedef enum {
    RECORD_VALID,
    RECORD_CORRUPT,
    RECORD_INVALID_HEADER,
    RECORD_HEADER_BOUNDS,
    RECORD_CRC_INVALID,
    RECORD_INVALID_COMMIT,
    RECORD_INVALID,
    RECORD_NO_EXIST,
    RECORD_READ_ERROR
} record_state;

#endif